import Link from "next/link";
import { entryMedia, searchCommunity, searchContributors, type SearchInput } from "@/lib/community/server";
import Identity from "./Identity";
import FeedFilters from "./FeedFilters";
import { EntryCard } from "./EntryCard";
export { EntryCard } from "./EntryCard";
export default async function Feed({ query, path, prompts = false }: { query: Record<string, string | string[] | undefined>; path: string; prompts?: boolean }) {
  const q = typeof query.q === "string" ? query.q.slice(0, 180) : ""; const kind = prompts ? "prompt" : typeof query.kind === "string" ? query.kind : "experiences"; const category = typeof query.category === "string" ? query.category : "";
  const page = Math.max(1, Math.min(500, Number(query.page) || 1));
  let result; let error = "";
  try { result = await searchCommunity({ q, kind, category, page } as SearchInput); const media = await entryMedia(result.entries.map(e => e.id)); result.entries = result.entries.map(e => ({ ...e, media: media.filter(m => m.entry_id === e.id) })); } catch (e) { error = e instanceof Error ? e.message : "Discussions are unavailable."; }
  const pageUrl = (p: number) => `${path}?${new URLSearchParams({ q, kind, category, page: String(p) })}`;
  const discovery = q && !prompts && kind === "experiences" && !category && page === 1 ? await searchContributors(q).catch(() => null) : null;
  return <div className="cq-grid"><section><div className="cq-feed-heading"><h2>{prompts ? "Community prompts" : "Latest discussions"}</h2><Link prefetch={false} className="cq-button cq-button-primary" href={prompts ? "/share?type=prompt" : "/share"}>Share {prompts ? "a prompt" : "a post"} ↗</Link></div><FeedFilters path={path} q={q} kind={kind} category={category} prompts={prompts} />
    {error ? <p role="alert" className="cq-notice cq-error">{error} <Link prefetch={false} className="cq-text-link" href={path}>Try again</Link></p> : !result?.available ? <div className="cq-empty"><h2>A place for useful AI conversations.</h2><p>Community publishing is being prepared. Explore the guidelines and plan your first contribution.</p><Link prefetch={false} href="/community/guidelines" className="cq-button">Read the guidelines ↗</Link></div> : result.entries.length ? <div className="cq-stack">{result.entries.map(e => <EntryCard key={e.id} entry={e} />)}</div> : <div className="cq-empty"><h2>{q ? "No matching discussions yet." : "Start a useful conversation."}</h2><p>{q ? "Try a different tool, phrase or category." : "Share the context, the experiment and what you learned. Clear questions are welcome too."}</p><Link prefetch={false} className="cq-button" href={q ? path : `/share${prompts ? "?type=prompt" : ""}`}>{q ? "Clear search" : "Share something ↗"}</Link></div>}
    {(page > 1 || result?.more) && <nav className="cq-pagination" aria-label="Results pages">{page > 1 && <Link prefetch={false} className="cq-button" href={pageUrl(page - 1)}>Previous</Link>}<span>Page {page}</span>{result?.more && <Link prefetch={false} className="cq-button" href={pageUrl(page + 1)}>Next</Link>}</nav>}
    {discovery && discovery.people.length > 0 && <section aria-label="Matching profiles"><h2 className="cq-section-title">Profiles</h2><div className="cq-stack">{discovery.people.map(p => <div key={p.id} className="cq-panel"><p className="cq-kicker">Profile</p><Identity profile={p} /><p className="cq-hint">{p.bio}</p></div>)}</div></section>}
    {discovery && discovery.answers.length > 0 && <section aria-label="Matching answers"><h2 className="cq-section-title">Answers</h2><div className="cq-stack">{discovery.answers.map(e => <EntryCard key={e.id} entry={e} />)}</div></section>}
  </section><aside className="cq-aside"><div className="cq-panel"><p className="cq-kicker">Create · Build · Automate</p><h2>What did you try?</h2><p>Questions, experiments and practical workflows from people using AI.</p><ul><li>Give enough context to help.</li><li>Show the result, including limits.</li><li>Credit the original creator.</li></ul><Link prefetch={false} className="cq-button cq-button-primary" href={prompts ? "/share?type=prompt" : "/share"}>Share with the community ↗</Link></div><div className="cq-panel"><h2>{prompts ? "Zqtion Original" : "Start with a useful brief."}</h2><p>{prompts ? "Explore the existing curated library, with editable briefs and prompting methods." : "Explore original prompts for creative work, interfaces and coding."}</p><Link prefetch={false} className="cq-button" href="/prompts">Explore the Prompt Library ↗</Link></div></aside></div>;
}
