import Link from "next/link";
import { notFound } from "next/navigation";
import { getCategories, getPromptMethods, getTools } from "@/lib/prompts/service";
import { promptMetadata } from "@/lib/prompts/seo";
import { LibraryBreadcrumbs, LibraryHeader, LibrarySeo } from "@/components/prompts/LibraryShell";
import Collection, { type SearchParams } from "@/components/prompts/Collection";

function info(slug: string) {
  if (slug === "methods") return { title: "Prompting methods", description: "Learn how to structure a brief, direct an image and define a verifiable coding task." };
  if (slug === "tools") return { title: "Prompts by tool", description: "Find editable Zqtion briefs for your coding or image workflow, with practical usage notes and clear limitations." };
  if (slug === "methodology") return { title: "How we make this library", description: "Our approach to private research, original prompt writing, quality checks and honest previews." };
  return getCategories().find((c) => c.slug === slug);
}
type Props = { params: Promise<{ category: string }>; searchParams: Promise<SearchParams> };
export async function generateMetadata({ params }: Props) { const { category } = await params; const page = info(category); return page ? promptMetadata(page.title, page.description, `/prompts/${category}`) : {}; }
export default async function CategoryPage({ params, searchParams }: Props) {
  const { category } = await params; const page = info(category); if (!page) notFound();
  const record = getCategories().find((c) => c.slug === category);
  return <><LibraryBreadcrumbs items={[{ name: "Prompts", path: "/prompts" }, { name: page.title, path: `/prompts/${category}` }]} /><LibrarySeo title={page.title} description={page.description} path={`/prompts/${category}`} article={category === "methodology"} /><LibraryHeader title={page.title} description={page.description} />
    {record ? <><section className="pl-category-intro"><div><h2>What belongs in the brief?</h2><p>{record.definition}</p><p>{record.include}</p></div><div><h2>Put it to work</h2><p>{record.usage}</p><Link className="pl-action" href={`/prompts/methods/${record.method}`}>Learn the {record.title.toLowerCase()} framework ↗</Link></div></section><Collection query={await searchParams} category={category} /></> : category === "methods" ? <div className="pl-guide-grid">{getPromptMethods().map((m, i) => <article key={m.slug}><p className="pl-kicker">METHOD / 0{i + 1}</p><h2><Link href={`/prompts/methods/${m.slug}`}>{m.title} ↗</Link></h2><p>{m.description}</p><div className="pl-formula-small">{m.formula.slice(0, 4).join(" → ")}</div></article>)}</div>
    : category === "tools" ? <div className="pl-guide-grid">{getTools().map((t) => <article key={t.slug}><p className="pl-kicker">WORKFLOW GUIDE</p><h2><Link href={`/prompts/tools/${t.slug}`}>{t.title} ↗</Link></h2><p>{t.description}</p><p className="pl-small">{t.limitation}</p></article>)}</div>
    : <div className="pl-prose"><section><h2>Research patterns, then write a new brief</h2><p>We inspect privately collected research to identify general techniques: information hierarchy, coherent lighting, clear constraints and useful prompt structure. The public library contains separately authored Zqtion tasks and explanations. Source prompt bodies, scraped files and source screenshots are not served by this website.</p></section><section><h2>Give every prompt a distinct job</h2><p>A prompt needs a specific user, a practical outcome and checks that make the result reviewable. We avoid creating extra pages by swapping a colour, product name or adjective. Customization fields handle those changes within the same brief.</p></section><section><h2>What we check</h2><p>Offline validation checks required fields, stable URLs, duplicate content, variables, formatting and metadata. A lexical screening compares the authored prompts against the available source bodies for phrase overlap, long matching sequences, normalized word similarity and repeated heading structure.</p><p>These checks can flag copying risks; they do not prove semantic originality or grant rights to source material. General patterns inform research, while the source expression stays private.</p></section><section><h2>What we have not tested</h2><p>We have checked the website and prompt structure. We have not run a model-by-model evaluation of every prompt. Tool labels describe an intended workflow, and expected examples explain what to look for; they are not recorded generation results. Review each output before using it in a real project.</p></section><section><h2>Previews and updates</h2><p>The preview visuals are lightweight original illustrations made for this library. They show composition or interface direction and are labelled as concepts. They are not copied screenshots or claims about what a model produced.</p><p>Prompt dates change when the authored content changes. To suggest a correction, <Link href="/contact">contact Zqtion</Link> with the prompt title, tool and the specific result that did not meet the brief.</p></section><section><h2>Keep the judgment human</h2><p>Zqtion is a founder-led AI execution company for creative production, digital products and practical automation. This library makes briefs easier to understand and reuse; it does not replace product judgment, factual review or implementation testing.</p><Link className="pl-action" href="/prompts/methods">Explore the prompting methods ↗</Link></section></div>}
  </>;
}
