import { CommunityHeader } from "@/components/community/CommunityShell";
import { communityMetadata } from "@/lib/community/seo";
export const metadata = communityMetadata("Community guidelines", "How to participate in Zqtion Community: useful context, attribution, privacy, respectful discussion and human moderation.", "/community/guidelines", true);
const sections = [
  ["Share evidence and context", "Explain what you tried, the AI tool involved, what happened and what you still do not know. Separate an observed result from a claim. Do not invent tool failures, credentials, endorsements or outcomes."],
  ["Be respectful", "Challenge ideas without harassing people. Threats, hate, sexual exploitation, graphic violence, doxxing and abusive promotion are not allowed. Do not impersonate another person or imply that Zqtion has verified your identity."],
  ["Keep private information private", "Do not post passwords, API keys, financial details, home addresses, private emails, client data or another person’s private information. Check screenshots and image backgrounds before uploading. Public contributions can be copied by others."],
  ["Credit the source and respect rights", "Only upload images and text you have permission to share. Disclose AI-generated results and relevant limitations. Remix community prompts using the Remix action so the original remains credited. Sharing permits other community members to discuss and remix your prompt with attribution; it does not remove third-party rights."],
  ["Make technical discussion useful", "Legitimate security education, debugging and discussion of AI limitations are welcome. Malware distribution, scams, exploitative material and instructions targeting another person are not. Automated rules may queue an educational post; moderators review context."],
  ["Understand moderation", "Verified email and a completed profile are required for participation. Uploaded images and text flagged by deterministic rules are held for manual review. Reports are private to moderators. Moderators may hide content, approve reviewed submissions or restrict an account, with an audit record. Rules cannot detect every harmful image or claim."],
  ["Edit, delete and appeal", "You can edit your own available contributions and remove them from public view. Removing a parent discussion also hides its conversation. Moderation records and private reports may remain for abuse prevention. For an appeal, account deletion or privacy request, contact info@zqtion.com. Include the contribution link; do not send passwords."],
  ["Keep it focused", "No spam, duplicate flooding, paid promotion disguised as advice or unsupported promises. Search for related discussions first. A related question is welcome when it has its own context. One verified account has one vote and one rating per contribution."],
];
export default function Page() { return <><CommunityHeader title="Useful, honest, respectful." description="Community guidelines · Version 2026-09-v1. These guidelines apply to profiles, posts, answers, comments, prompts, remixes and images." /><div className="cq-guidelines">{sections.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}</div></>; }
