alter table public.website_inquiries
  add column if not exists project_url text,
  add column if not exists landing_path text,
  add column if not exists referrer text,
  add column if not exists utm_source text,
  add column if not exists utm_medium text,
  add column if not exists utm_campaign text,
  add column if not exists utm_content text;

create table if not exists public.website_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null check (char_length(event_name) between 2 and 80),
  path text not null,
  session_id text,
  landing_path text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.website_events enable row level security;

create index if not exists website_events_created_at_idx on public.website_events (created_at desc);
create index if not exists website_events_name_created_at_idx on public.website_events (event_name, created_at desc);

create table if not exists public.website_rate_limits (
  key_hash text not null,
  window_start timestamptz not null,
  attempt_count integer not null default 1 check (attempt_count > 0),
  primary key (key_hash, window_start)
);

alter table public.website_rate_limits enable row level security;

create or replace function public.consume_website_inquiry_rate_limit(
  p_key_hash text,
  p_window_seconds integer default 600,
  p_max_attempts integer default 5
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_window timestamptz;
  current_attempts integer;
begin
  if p_key_hash is null or char_length(p_key_hash) < 32 then
    return false;
  end if;

  current_window := to_timestamp(
    floor(extract(epoch from now()) / greatest(p_window_seconds, 60)) * greatest(p_window_seconds, 60)
  );

  insert into public.website_rate_limits (key_hash, window_start, attempt_count)
  values (p_key_hash, current_window, 1)
  on conflict (key_hash, window_start)
  do update set attempt_count = public.website_rate_limits.attempt_count + 1
  returning attempt_count into current_attempts;

  if random() < 0.02 then
    delete from public.website_rate_limits where window_start < now() - interval '2 days';
  end if;

  return current_attempts <= greatest(p_max_attempts, 1);
end;
$$;

revoke all on table public.website_events from anon, authenticated;
revoke all on table public.website_rate_limits from anon, authenticated;
revoke all on function public.consume_website_inquiry_rate_limit(text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_website_inquiry_rate_limit(text, integer, integer) to service_role;

-- All writes use the server-only service role. No public read policies are created.
